name = "iotpro"
pages_build_output_dir = "." #"public"
compatibility_date = "2025-11-02"

# --- D1 Database Binding (for storing ads) ---
[[d1_databases]]
binding = "NDB"
database_name = "iotpro"
database_id = "b03ce1d7-c83e-4ab7-a636-fef9e345694c"

# --- KV Namespace Binding (for caching / metadata) ---
[[kv_namespaces]]
binding = "USERS"
id = "5867a4f1be824058ae7365d1b20ed815"
